import streamlit as st

st.markdown(
    """
    <div class="hero-banner">
        <h1>🥗 AI-Powered Nutrition Planner</h1>
        <p>Your intelligent companion for personalised meal planning &amp; food analysis</p>
    </div>
    """,
    unsafe_allow_html=True,
)

st.markdown(
    """
    Welcome to **AI-Powered Nutrition Planner** — an intelligent application that
    combines the power of large language models and computer vision to help you
    eat healthier, hit your fitness goals, and understand what's on your plate.
    """
)

st.divider()

st.markdown('<p class="section-header">✨ Key Features</p>', unsafe_allow_html=True)

col1, col2, col3 = st.columns(3, gap="large")

with col1:
    st.markdown(
        '<div class="glass-card"><h3>🍽️ Smart Meal Planning</h3>'
        '<p>Get a complete <b>7-day meal plan</b> with breakfast, lunch, dinner, and snacks — '
        'generated by Llama&nbsp;3.3 via Groq. Every meal includes calorie &amp; macro breakdowns.</p></div>',
        unsafe_allow_html=True,
    )

with col2:
    st.markdown(
        '<div class="glass-card"><h3>📸 Food Analyser</h3>'
        '<p>Upload a photo of any food and let our <b>CLIP vision model</b> identify it instantly. '
        'Supports <b>200+ foods</b> across international cuisines.</p></div>',
        unsafe_allow_html=True,
    )

with col3:
    st.markdown(
        '<div class="glass-card"><h3>🎯 Personalised Goals</h3>'
        '<p>Enter your age, weight, height, activity level, and fitness goal. '
        'The app calculates your <b>BMR &amp; TDEE</b> to tailor the plan just for you.</p></div>',
        unsafe_allow_html=True,
    )

st.write("")

st.markdown('<p class="section-header">🚀 How It Works</p>', unsafe_allow_html=True)

col_a, col_b = st.columns(2, gap="large")

with col_a:
    st.markdown(
        """
        **Meal Planner**
        1. Fill in your body metrics & dietary preferences
        2. The app calculates your BMR using the **Harris-Benedict** equation
        3. A detailed prompt is sent to **Groq (Llama 3.3 70B)**
        4. You receive a structured 7-day meal plan with full macros
        5. Don't like something? Add feedback & regenerate!
        """
    )

with col_b:
    st.markdown(
        """
        **Food Analyser**
        1. Navigate to the **Food Analyser** page
        2. Upload a photo of any food item
        3. The **CLIP** model classifies the image against 200+ foods
        4. See the identified food name and confidence score
        """
    )

st.divider()

st.info(
    "👉 Use the **sidebar** to navigate between pages. "
    "Head to **Meal Planner** to generate your first personalised plan, "
    "or try the **Food Analyser** to identify a food photo!",
    icon="💡",
)

with st.expander("📋 Setup Instructions"):
    st.markdown(
        """
        1. **Install dependencies** — `pip install -r requirements.txt`
        2. **Create a `.env` file** with your Groq API key — `GROQ_API_KEY=gsk_xxx`
        3. **Run the app** — `python -m streamlit run app.py`
        """
    )

st.markdown(
    '<div class="app-footer">Built with ❤️ using Streamlit · Groq · HuggingFace Transformers</div>',
    unsafe_allow_html=True,
)
